// Generated by gencpp from file fiducial_msgs/IdArray.msg
// DO NOT EDIT!


#ifndef FIDUCIAL_MSGS_MESSAGE_IDARRAY_H
#define FIDUCIAL_MSGS_MESSAGE_IDARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fiducial_msgs
{
template <class ContainerAllocator>
struct IdArray_
{
  typedef IdArray_<ContainerAllocator> Type;

  IdArray_()
    : ids()  {
    }
  IdArray_(const ContainerAllocator& _alloc)
    : ids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _ids_type;
  _ids_type ids;





  typedef boost::shared_ptr< ::fiducial_msgs::IdArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fiducial_msgs::IdArray_<ContainerAllocator> const> ConstPtr;

}; // struct IdArray_

typedef ::fiducial_msgs::IdArray_<std::allocator<void> > IdArray;

typedef boost::shared_ptr< ::fiducial_msgs::IdArray > IdArrayPtr;
typedef boost::shared_ptr< ::fiducial_msgs::IdArray const> IdArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fiducial_msgs::IdArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fiducial_msgs::IdArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fiducial_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'fiducial_msgs': ['/home/ubuntu/catkin_ws/src/fiducials/fiducial_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fiducial_msgs::IdArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fiducial_msgs::IdArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fiducial_msgs::IdArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fiducial_msgs::IdArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fiducial_msgs::IdArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fiducial_msgs::IdArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fiducial_msgs::IdArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f22efebf407aadba2ecc69df353d113";
  }

  static const char* value(const ::fiducial_msgs::IdArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f22efebf407aadbULL;
  static const uint64_t static_value2 = 0xa2ecc69df353d113ULL;
};

template<class ContainerAllocator>
struct DataType< ::fiducial_msgs::IdArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fiducial_msgs/IdArray";
  }

  static const char* value(const ::fiducial_msgs::IdArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fiducial_msgs::IdArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Id Array to store found fiducials\n\
\n\
int32[] ids\n\
";
  }

  static const char* value(const ::fiducial_msgs::IdArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fiducial_msgs::IdArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IdArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fiducial_msgs::IdArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fiducial_msgs::IdArray_<ContainerAllocator>& v)
  {
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIDUCIAL_MSGS_MESSAGE_IDARRAY_H
